"""Create deploy/.env with random local secrets, if it doesn't exist yet.

Docker Compose reads deploy/.env automatically. The file is gitignored; never commit it.
Re-running is a no-op so existing database volumes keep matching their passwords.
"""

import secrets
import sys
from pathlib import Path

ENV_FILE = Path(__file__).resolve().parent.parent / "deploy" / ".env"
SECRETS = (
    "POSTGRES_PASSWORD",  # superuser: migrations only
    "CONSUMER_DB_PASSWORD",  # telemetry_writer role
    "GRAFANA_DB_PASSWORD",  # grafana_reader role (read-only)
    "GRAFANA_ADMIN_PASSWORD",
)


def main() -> int:
    if ENV_FILE.exists():
        print(f"{ENV_FILE.name} exists; leaving it unchanged")
        return 0
    lines = ["# Generated by scripts/gen_env.py. Local secrets; do not commit."]
    lines += [f"{name}={secrets.token_urlsafe(24)}" for name in SECRETS]
    lines += [
        "# Ingest API key used by the replayer by default. Change it if anything but",
        "# your own machine can reach port 8000.",
        "INGEST_API_KEYS=dev-key",
    ]
    ENV_FILE.write_text("\n".join(lines) + "\n")
    ENV_FILE.chmod(0o600)
    print(f"wrote {ENV_FILE} (Grafana admin password is in there)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
