"""Create deploy/.env with random local secrets, or add any that are missing.

Docker Compose reads deploy/.env automatically. The file is gitignored; never commit it.
Existing values are never changed, so database volumes keep matching their passwords.
"""

import secrets
import sys
from pathlib import Path

ENV_FILE = Path(__file__).resolve().parent.parent / "deploy" / ".env"
SECRETS = (
    "POSTGRES_PASSWORD",  # superuser: migrations only
    "CONSUMER_DB_PASSWORD",  # telemetry_writer role
    "GRAFANA_DB_PASSWORD",  # grafana_reader role (read-only)
    "GRAFANA_ADMIN_PASSWORD",
    "DETECTOR_DB_PASSWORD",  # incident_detector role
    "KNOWLEDGE_DB_PASSWORD",  # knowledge_service role
    "KNOWLEDGE_API_KEY",  # clients of the knowledge API (the agent in A5)
    "AGENT_DB_PASSWORD",  # incident_agent role
    "APPROVAL_DB_PASSWORD",  # approval_service role (decides approval requests)
    "AGENT_API_KEY",  # clients of the agent API
    "SLACK_BOT_API_KEY",  # the Slack bot's key for the agent API (acts only for linked users)
    "DEMO_APPROVER_PASSWORD",  # `make demo-users`: local accounts for trying the web UI
    "DEMO_VIEWER_PASSWORD",
)


def main() -> int:
    existing = ENV_FILE.read_text() if ENV_FILE.exists() else ""
    present = {line.split("=", 1)[0] for line in existing.splitlines() if "=" in line}
    if not existing:
        lines = ["# Generated by scripts/gen_env.py. Local secrets; do not commit."]
        lines += [f"{name}={secrets.token_urlsafe(24)}" for name in SECRETS]
        lines += [
            "# Ingest API key used by the replayer by default. Change it if anything but",
            "# your own machine can reach port 8000.",
            "INGEST_API_KEYS=dev-key",
        ]
        ENV_FILE.write_text("\n".join(lines) + "\n")
        ENV_FILE.chmod(0o600)
        print(f"wrote {ENV_FILE} (Grafana admin password is in there)")
        return 0
    missing = [name for name in SECRETS if name not in present]
    if missing:
        with ENV_FILE.open("a") as f:
            f.write("".join(f"{name}={secrets.token_urlsafe(24)}\n" for name in missing))
        print(f"added {', '.join(missing)} to {ENV_FILE.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
