# ------------------------------------------------------------------------- secrets: Key Vault
# Every secret the chart reads, generated here and stored in Key Vault. External Secrets copies
# them into the cluster; nothing secret goes through Git, Helm values or CI variables.
locals {
  generated_secrets = toset([
    "CONSUMER_DB_PASSWORD", "GRAFANA_DB_PASSWORD", "DETECTOR_DB_PASSWORD",
    "KNOWLEDGE_DB_PASSWORD", "AGENT_DB_PASSWORD", "APPROVAL_DB_PASSWORD",
    "KNOWLEDGE_API_KEY", "AGENT_API_KEY", "SLACK_BOT_API_KEY", "INGEST_API_KEYS",
  ])
  # Key Vault names: ia-<key in lower-kebab-case>, matching secrets.externalSecrets in the chart.
  kv_name = { for k in local.generated_secrets : k => "ia-${replace(lower(k), "_", "-")}" }
}

resource "random_password" "app" {
  for_each = local.generated_secrets
  length   = 32
  special  = false
}

resource "azurerm_key_vault" "main" {
  name                       = substr(replace("${var.name}-kv", "-", ""), 0, 24)
  resource_group_name        = azurerm_resource_group.main.name
  location                   = azurerm_resource_group.main.location
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "standard"
  rbac_authorization_enabled = true
  purge_protection_enabled   = true
  soft_delete_retention_days = 7
  tags                       = var.tags

  network_acls {
    default_action             = "Deny"
    bypass                     = "None"
    ip_rules                   = var.admin_ip_ranges     # Terraform writes secrets
    virtual_network_subnet_ids = [azurerm_subnet.aks.id] # External Secrets reads them
  }
}

# Whoever runs Terraform writes the secrets.
resource "azurerm_role_assignment" "kv_admin" {
  scope                = azurerm_key_vault.main.id
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "azurerm_key_vault_secret" "app" {
  for_each     = local.generated_secrets
  name         = local.kv_name[each.key]
  value        = random_password.app[each.key].result
  key_vault_id = azurerm_key_vault.main.id
  content_type = "generated by terraform"
  depends_on   = [azurerm_role_assignment.kv_admin]
}

resource "azurerm_key_vault_secret" "postgres_admin" {
  name         = "ia-postgres-password"
  value        = random_password.postgres_admin.result
  key_vault_id = azurerm_key_vault.main.id
  content_type = "generated by terraform"
  depends_on   = [azurerm_role_assignment.kv_admin]
}

# External Secrets Operator reads Key Vault as this identity, through workload identity.
resource "azurerm_user_assigned_identity" "external_secrets" {
  name                = "${var.name}-external-secrets"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  tags                = var.tags
}

resource "azurerm_federated_identity_credential" "external_secrets" {
  name                      = "external-secrets"
  user_assigned_identity_id = azurerm_user_assigned_identity.external_secrets.id
  audience                  = ["api://AzureADTokenExchange"]
  issuer                    = azurerm_kubernetes_cluster.main.oidc_issuer_url
  subject                   = "system:serviceaccount:external-secrets:external-secrets"
}

resource "azurerm_role_assignment" "external_secrets_kv" {
  scope                = azurerm_key_vault.main.id
  role_definition_name = "Key Vault Secrets User" # read-only
  principal_id         = azurerm_user_assigned_identity.external_secrets.principal_id
}

# ------------------------------------------------------------- deploys: GitHub Actions via OIDC
# The deploy workflow logs in with a short-lived token GitHub issues for this repo's
# environment; no client secret exists anywhere.
resource "azuread_application" "github" {
  display_name = "${var.name}-github-deploy"
}

resource "azuread_service_principal" "github" {
  client_id = azuread_application.github.client_id
}

resource "azuread_application_federated_identity_credential" "github" {
  application_id = azuread_application.github.id
  display_name   = "github-${var.github_environment}"
  audiences      = ["api://AzureADTokenExchange"]
  issuer         = "https://token.actions.githubusercontent.com"
  subject        = "repo:${var.github_repository}:environment:${var.github_environment}"
}

resource "azurerm_role_assignment" "github_push" {
  scope                = azurerm_container_registry.main.id
  role_definition_name = "AcrPush"
  principal_id         = azuread_service_principal.github.object_id
}

resource "azurerm_role_assignment" "github_aks_user" {
  scope                = azurerm_kubernetes_cluster.main.id
  role_definition_name = "Azure Kubernetes Service Cluster User Role"
  principal_id         = azuread_service_principal.github.object_id
}

# Enough to helm install into the cluster; not cluster admin.
resource "azurerm_role_assignment" "github_aks_writer" {
  scope                = azurerm_kubernetes_cluster.main.id
  role_definition_name = "Azure Kubernetes Service RBAC Writer"
  principal_id         = azuread_service_principal.github.object_id
}

# ------------------------------------------------------------------------------------- budget
resource "azurerm_consumption_budget_resource_group" "main" {
  count             = var.budget_alert_email == "" ? 0 : 1
  name              = "${var.name}-budget"
  resource_group_id = azurerm_resource_group.main.id
  amount            = var.budget_monthly_usd
  time_grain        = "Monthly"
  time_period { start_date = formatdate("YYYY-MM-01'T'00:00:00Z", plantimestamp()) }
  dynamic "notification" {
    for_each = [50, 80, 100]
    content {
      enabled        = true
      threshold      = notification.value
      operator       = "GreaterThanOrEqualTo"
      contact_emails = [var.budget_alert_email]
    }
  }
  lifecycle { ignore_changes = [time_period] }
}
